version: "3"

services:

  master:
    build:
      context: ./docker/jenkins/master
    ports:
      - "80:8080"
    environment:
      - JAVA_OPTS=-Xmx2048m
      - JENKINS_USERNAME=admin
      - JENKINS_PASSWORD=cvf,bo
      - JENKINS_UC_DOWNLOAD=http://mirrors.jenkins-ci.org
    volumes:
      - ./docker/jenkins/master/data:/opt
      - ./docker/jenkins/master/home:/var/jenkins_home

  slave:
    build:
      context: ./docker/jenkins/slave
    environment:
      - JAVA_OPTS=-Xmx2048m
      - JENKINS_MASTER=http://master:8080
      - JENKINS_SLAVE_NAME=slave
      - JENKINS_USERNAME=admin
      - JENKINS_PASSWORD=cvf,bo
      - JENKINS_EXECUTORS=5
      - JENKINS_RETRY=10
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock